/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {

    Pessoa[] bancoCadastro = new Pessoa[100];
    private int bancoID = 0;
   

    public static void main(String[] args) {

        Pessoa p1= new Pessoa("Gabriel", "gabriel.lw09@aluno.ifsc.edu.br");
        Pessoa p2= new Pessoa("Gabriel", "gabriel.lw09@aluno.ifsc.edu.br");
        Pessoa p3= new Pessoa("Gabriel", "gabriel.lw09@aluno.ifsc.edu.br");
        Pessoa p4= new Pessoa("Gabriel", "gabriel.lw09@aluno.ifsc.edu.br");

        



        App app = new App();
        

        String option;
        boolean running = true;
        do { 
            option = app.showOptions();
            switch (option) {
            case "1" -> app.cadastrar();
            case "2" -> app.imprimirBancoTabela();
            case "3" -> app.imprimirPessoa();
            case "4" -> running = false;
            default -> System.out.println("OPÇÃO INVÁLIDA");
            }
        } while (running);









    }

    private String showOptions(){
        System.out.println("1 - Cadastrar\n2 - Listar Pessoas\n3 - Imprimir dados de uma pessoa\n4 - sair");
        String option = IO.readln("option: ");
        return option;

        


    }



    private void cadastrar(){
        String nome = IO.readln("Nome: ");
        String Email = IO.readln("Email: ");
        bancoCadastro[bancoID] = new Pessoa(nome, Email);
        bancoID++;


    }

    private void imprimirBancoTabela(){
        
        //arrumar a formatação
        System.out.println("|  ID  |              NOME              |              EMAIL              |");
        for (Pessoa pessoa : bancoCadastro) {
            
            System.out.println(String.format("|%6d|%32s|%33s|", pessoa.getId(), pessoa.getNome(), pessoa.getEmail()));
        }
    }

    private void imprimirPessoa(){

    }
}
