/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.HashSet;

public class App {
    

    public static void main(String[] args) {
        // ArrayList<String> lista = new ArrayList<>();

        // lista.add("POO");
        // lista.add("ADS");
        // lista.add("ADS");
        // lista.add("IFSC");
        // lista.add("SJE");
        
        // for (int i = 0; i < lista.size();i++) {
        //     IO.println(lista.get(i));
        // }

        // for (String elemento : lista){

        //     System.out.println(elemento);

        // }

        // lista.forEach(e -> System.out.println(e));

        // lista.forEach(IO::println);

        // //remove todos os "ADS"
        // lista.removeIf(e -> e.equals("ADS"));
        // System.out.println();
        // lista.forEach(e -> System.out.println(e));







        // ArrayList<Pessoa> agenda = new ArrayList<>();
        HashSet<Pessoa> agenda = new HashSet<>();

        agenda.add(new Pessoa("Juca", "juc5459@aluno.ifsc.edu.br"));
        agenda.add(new Pessoa("gabriel", "gabriel.lw09@aluno.ifsc.edu.br"));
        agenda.add(new Pessoa("zézinho", "zédamanga@aluno.ifsc.edu.br"));
        agenda.add(new Pessoa("binóculos", "binóculos.lw09@aluno.ifsc.edu.br"));
        agenda.add(new Pessoa("Juca", "jucaaa.lw09@aluno.ifsc.edu.br"));
        Pessoa p = new Pessoa("zézinho", "zédamanga@aluno.ifsc.edu.br");

        agenda.remove(p);

        agenda.forEach(e -> System.out.println(e.getNome()));

        agenda.removeIf(e -> e.getNome().equals("Juca"));

        System.out.println();

        agenda.forEach(e -> System.out.println(e.getNome()));

    }
}
