/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;
import java.util.Random;
import java.util.random.*;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Random random = new Random();
        boolean playing = true;

        do {
            String entrada;
            int guess = 0;
            int count = 0;
            int secretNumber = random.nextInt(1,101);
            do {
                entrada = (IO.readln("Entre com um número de 1-100: "));

               try{
                   guess = Integer.parseInt(entrada);
                }
               catch(RuntimeException e){
                   continue;
               }
                guess = Integer.parseInt(entrada);
                if (guess == secretNumber) {
                    System.out.println("Você ACERTOU!");
                    System.out.println("tentativas: "+ count);
                    break;

                }
                else if(guess < secretNumber){
                    System.out.println("maior");
                    count++;
                }
                else if(guess > secretNumber){
                    System.out.println("menor");
                    count++;
                }

            } while (!(entrada.equals("exit")));


            playing = (IO.readln("jogar novamente?(y/n): ").equals("y"))? true: false;
            count=0;

        }while(playing);
    }
}
