/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;
import java.util.Random;
import java.util.random.*
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Random random = new Random();
        boolean playing = true;
        int guess = 0;
        int count = 0;
        int secretNumber = random.nextInt(1,101);
        do {
            do {
                guess = Integer.parseInt(IO.readln("Entre com um número de 1-100: "));

                if (guess = secretNumber) {
                    System.out.println("Você ACERTOU!");

                    break;

                }


            } while (!(guess >= 1 || guess <= 100));
        }while(playing);
    }
}
