/*
 * This source file was generated by the Gradle 'init' task
 */

package ads.poo;
import java.util.Scanner;

public class App {
   
    public static void main(String[] args) {
        Scanner entrada = new Scanner(System.in);
        System.out.println("AAAAAAAAAAAAAAAAAAAAAAa");

        //não lê o arquivo por algum motivo
        while (entrada.hasNextInt()) {
            int valor = entrada.nextInt();
            System.out.println(valor);
            System.out.println("entrou");
            //nunca entra
        }

        //resolver depois

        
    }
}