/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ");
        String estacao = "";

        switch (mes){
            case "janeiro", "fevereiro" -> estacao = "verão";
            case "março" -> estacao = (dia<20)? "verão": "outono";
            case "abriu", "maio" -> estacao = "outono";
            case "junho" -> estacao = (dia<21)? "outono": "inverno";
            case "julho", "agosto" -> estacao = "inverno";
            case "setembro" -> estacao = (dia < 22)? "inverno":"primavera";
            case "outubro","novembro" -> estacao = "primavera";
            case "dezembro" -> estacao = (dia < 21)? "verão": "outono";
            default -> IO.println("Something went wrong!!");


        }

        IO.println("Estação atual: "+ estacao);
    }
}
