/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        String nome = IO.readln("Entre com seu nome: ");
        IO.println("OLá " + nome);

        int contador = 0;
       for(String aux : args){

           if(aux.equals("POO")){
               IO.println("Acertou!");
           }
           else{
               contador++;
           }
       }
        IO.println("total de argumentos diferentes de POO: "+contador);
    }
}
