/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    

    public static void main(String[] args) {
        
        Batedeira batedeira = new Batedeira();

        //alternar estado
        batedeira.ligarDesligar();
        batedeira.ligarDesligar();

        //garantir ligar
        if( ! batedeira.retornarEstado()){
            batedeira.ligarDesligar();
            System.out.println("Ligando...");
        }

        //bater
        if(batedeira.bater()){
            System.out.println("Batedeira Batendo com espatula " + batedeira.retornarEspatula());
        }
        else{
            System.out.println("batedeira desligada, não começou a bater");
        }

        //trocar espatula, nao pode ligada
        batedeira.trocarEspatula("Raquete");

        //desliga e troca
        batedeira.ligarDesligar();
        batedeira.trocarEspatula("Raquete");

        //ligando
        batedeira.ligarDesligar();


        if(batedeira.bater()){
            System.out.println("Batedeira Batendo com espatula " + batedeira.retornarEspatula());
        }
        else{
            System.out.println("batedeira desligada, não começou a bater");
        }

    }
}
