/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
  

    public static void main(String[] args) {
        Ponto p1 = new Ponto(13, 19);
        Ponto p2 = new  Ponto(5,11);

        System.out.println(Ponto.distanciaPontos(p1, p2));


    }
}
