/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
   

    public static void main(String[] args) {
        
        Retangulo rec = new  Retangulo();
        System.out.println();
        rec.setCodificacao("UTF8");
        System.out.println(rec.toString());
        
    }
}
