/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    

    public static void main(String[] args) {
        
        Motor v8 = new Motor(1,1);
        Carro fusca = new Carro("vw", v8);

        fusca = null;
        //motor continua existindo independentemente do Carro
        //agregação



        //composição
        //se destruir carro, destroi o motor tambem
        // se new Carro("marca", new Motor(1,1))
        //ou na instanciação na classe onde propulsor = new Motor(1,1)


        
    }
}
