/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
   
    public static void main(String[] args) {
        Contador contador = new Contador();
        IO.println(contador.obterValorAtual());
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        contador.incrementar();
        IO.println(contador.obterValorAtual());

        contador.atribuir( 57);
        IO.println(contador.obterValorAtual());
        

        
    }
}
