/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        switch (args[0]){
            case "triangulo" -> drawTriangulo(Integer.parseInt(args[1]));//chamar triangulo passando args[1]
            case "losango" -> drawLosango(Integer.parseInt(args[1])); //chamar losango passando args[1]
            case "retangulo" -> drawRetangulo(Integer.parseInt(args[1]), Integer.parseInt(args[2])); // chamar retangulo passando args[1] e args[2]
        }

        /*
        drawTriangulo(5);
        drawLosango(7);
        drawRetangulo(4, 5);
        */
        //refatorar depois usando .repeat da classe String

    }

    static void drawTriangulo(int altura){

        for(int i=0; i < altura; i++){
            for(int j=0; j<=i; j++){
                IO.print("*");
            }
            IO.println("");
        }

    }
    static void drawLosango(int altura){

        int camadas = 0;
        for(int i =altura; i>2; i-=2){
            camadas++;
        }

        //topo
        for(int i=1; i < altura/2.0; i++){
            for(int j=1; j<=altura; j++){
                if(j > camadas && j <= altura-camadas){
                    IO.print("*");
                }else{
                    IO.print(" ");
                }
            }
            camadas--;
            IO.println("");
        }

        //meio
        for(int i=0; i<altura; i++){
            IO.print("*");
        }
        IO.println("");

        //baixo
        camadas=1;
        for(int i=altura; i > 1; i--){
            for(int j=1; j<altura; j++){
                if(j > camadas && j <= altura-camadas){
                    IO.print("*");
                }else{
                    IO.print(" ");
                }
            }
            camadas++;
            IO.println("");
        }

    }

    static void drawRetangulo(int altura, int largura){

        for(int i=1; i<=altura;i++){
            for(int j=1; j<= largura; j++){
                if(i==1 || i== altura){
                    IO.print("*");
                }
                else if(j==1 || j== largura){
                    IO.print("*");
                }
                else{
                    IO.print(" ");
                }
            }
            IO.println("");
        }

    }

}
