/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    

    public static void main(String[] args) {
        Horario horario = new Horario(1,2,7);
        Horario horario2 = new Horario(1,3,9);
        System.out.println(horario.toString());
        System.out.println(horario.calcSegundos());

        System.out.println(Horario.difHorarios(horario, horario2));

    }
}
