/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.HashMap;

public class App {
    
    static HashMap<String, Livro> livrosCadastrados = new HashMap<>();
    public static void main(String[] args) {

        //chave, valor
        // HashMap<String,String> mapa = new HashMap<>();

        // mapa.put("123", "Juca");
        // mapa.put("456", "Ana");
        // mapa.put("789", "Pedro");
        // mapa.put("1423", "Juca");
        // mapa.put("1754", "Juca");
        // //se, substitui pedro
        // //mapa.put("789", "Joao");


        // String nome = mapa.get("456");

        // System.out.println(mapa.get("456"));




        // String nome2 = mapa.get("0000"); //null

        // if(nome2 == null){
        //     System.out.println("nao encontrado");
        // }else{
        //     System.out.println(nome2);
        // }


        // mapa.forEach((chave,valor) -> System.out.println("chave: "+chave+ "  Valor: "+valor));


        // for(var elemento : mapa.entrySet()){
        //     System.out.println("Chave: "+ elemento.getKey()+ "  Valor: "+ elemento.getValue());
        // }

        // mapa.remove("456");

        // mapa.values().removeIf(e -> e.equals("Juca"));


       cadastrarLivro();
      // cadastrarLivro();
      // cadastrarLivro();

       System.out.println();
       listarISBNeTitulo();

       System.out.println();
       System.out.println();

       consultarLivroISBN("1234567");




        



    }


    public static void cadastrarLivro(){
        String ISBN;
        System.out.println("");
        System.out.println("================================");
        do { 
            ISBN = IO.readln("ISBN: ");
        } while (livrosCadastrados.containsKey(ISBN));

        String titulo = IO.readln("Titulo: ");
        String autor = IO.readln("Autor: ");
        String dataDePublicacao = IO.readln("Data de Publicação(dd/mm/yy): ");
        livrosCadastrados.put(ISBN, new Livro(ISBN, titulo, autor, dataDePublicacao));
    }

    public static void removerLivro(String ISBN){

        livrosCadastrados.remove(ISBN); //precisa verificar se existe ?

    }

    public static void listarISBNeTitulo(){
        livrosCadastrados.forEach((k,v) -> System.out.println("ISBN:"+k+"  Título: "+v.getTitulo()));
    }

    public static void consultarLivroISBN(String ISBN){
        
        if(livrosCadastrados.get(ISBN) != null){
            Livro livro = livrosCadastrados.get(ISBN);
            System.out.println(livro);
        }else{
            System.out.println("ISBN não encontrado");
        }
    }

    public static void consultarLivroAutor(String autor){

        

        

    }

}
