/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Arrays;
import java.util.Random;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Random random = new Random();
        int tamanho = 9;
        int numAst = 10;
        int[] sortedNums = new int[numAst];
        for(int i=0; i<numAst;){

            int num = random.nextInt(1, (tamanho*tamanho)+1);

            for (int n : sortedNums){
                if (n == num){

                }
            }


            if(!(Arrays.stream(sortedNums).anyMatch(i))){
                sortedNums[i] = num;
                i++;
            }

        }

        for(int n : sortedNums){
            System.out.println(n);
        }


    }
}
