/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

import java.util.Arrays;
import java.util.List;
import java.util.Random;

public class App {
   

    public static void main(String[] args) {

        Random random = new Random();
        int tamanho = 9;
        int numAst = 10;
        int[] sortedNums = new int[numAst];
        for(int i=0; i<numAst;){

            int num = random.nextInt(1, (tamanho*tamanho)+1);

            boolean repetido=false;
            for(int j=1; j<sortedNums.length; j++){

                if(num == sortedNums[j]){
                    repetido = true;
                }

            }
            if(!repetido){
                sortedNums[i] = num;
                i++;
            }

        }

        for(int n : sortedNums){
            System.out.print(n+"  ");
        }
        System.out.println("\n\n");
        //10 unicos, 
        List<Integer> sortedList =  Arrays.stream(sortedNums).boxed().toList();
        
        for(int i=1; i<(tamanho*tamanho)+1;i++){
            
            

            if(sortedList.contains(i)){
                System.out.print("*");
            }
            else{
                System.out.print(".");

            }

            if((i%9) ==0){
                System.out.println();
            }
        }


    }
}
