/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    

    public static void main(String[] args) {
       
        Carro fusca = new Carro();
        
        fusca.acelerar(50);
        fusca.acelerar(49);
        fusca.acelerar(2);
        fusca.acelerar(80);
        

        IO.println(fusca.getVelocidadeAtual());



    }
}
