/*
 * This source file was generated by the Gradle 'init' task
 */
package ads.poo;

public class App {
    
    public static void main(String[] args) {
        Personagem player1 = new Personagem("eu", 100,27);

        player1.definirNome("OutroNome");

        IO.println(player1.obterNome() + " Atacked: " + player1.Atacar());

        

    }
}
